site_name: 'The Yapp Store - Developer Docs'
site_description: "Developer Documentation"
site_url: 'https://docs.yappstore.ai'
repo_name: 'docs'
repo_url: 'https://github.com/yappstore/docs'

############################################################################################

nav:
  - Home: index.md
  - Documentation: 
    - developer_notes/index.md
    # - Operations:
    #   - Github: 
    #     - Git Introduction: developer_notes/operations/git/git_intro.md
    #     - Actions: developer_notes/operations/git/git_actions.md

############################################################################################

extra_css:
  - stylesheets/extra.css
theme:
  name: material
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  custom_dir: docs/templates
  logo: https://raw.githubusercontent.com/akkupy/akkupy/main/assets/favicon.ico
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
    - navigation.instant
    - navigation.tracking
  # palette:
  #   - media: "(prefers-color-scheme: dark)"
  #     scheme: default
  #     toggle:
  #       icon: material/toggle-switch-off-outline
  #       name: Switch to dark mode
  #   - media: "(prefers-color-scheme: dark)" 
  #     scheme: slate
  #     toggle:
  #       icon: material/toggle-switch
  #       name: Switch to light mode
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to system preference
  # icon:
  #   admonition: 
  #     example: fontawesome/solid/flask


markdown_extensions:
  - admonition
  - def_list
  - attr_list
  # - callouts
  - footnotes
  - md_in_html
  - meta
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true 
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: "¤"


plugins:
  # - markdown-exec
  - search:
      lang: en
  - mkdocs-video:
      is_video: True
      video_muted: False
      video_controls: True
      css_style:
        width: "50%"

extra:
  analytics:
    provider: google
    property: G-VHR0GFBR7Q
  generator: false
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/theyappstore
  - icon: fontawesome/brands/twitter
    link: /
  - icon: fontawesome/brands/discord
    link: https://discord.com/

copyright: Copyright © 2024 The Yapp Store
