site_name: "The Yapp Store | Developer Documentation"
site_description: "Developer Documentation"
site_url: "https://docs.yappstore.ai"
repo_name: "docs"
repo_url: "https://github.com/yappstore/docs"

############################################################################################

nav:
  - Documentation:
      - content/overview/getting_started.md
      - Guides:
        - content/overview/guides/submission.md
        - content/overview/guides/updater.md
      - content/overview/roadmap.md
  - SDK:
      - content/sdk/sdk.md
      - Native API:
        - content/sdk/native_api/filesystem.md
        - content/sdk/native_api/shell.md
  - Monetization:
      - content/monetization/monetization.md
      - content/monetization/subscriptions/subscription.md
      - content/monetization/onetime/onetime.md
  - Security:
      - content/security/security.md
      - content/security/review.md
      - content/security/faq.md
  - About:
    - content/about/about.md
    - Boring Disclaimer Stuff:
      - content/about/tc.md
      - content/about/safety_agreement.md
  - Contact Us:
    - content/contact/contact.md

############################################################################################

extra_css:
  - stylesheets/extra.css
theme:
  name: material
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  custom_dir: docs/templates
  logo: https://raw.githubusercontent.com/yappstore/docs/main/favicon.png
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    # - navigation.instant
    - search.highlight
    - search.suggest
    - toc.follow

  palette:
    # - media: "(prefers-color-scheme: dark)"
    #   scheme: slate
    #   primary: black
    #   accent: pink
    #   toggle:
    #     icon: material/weather-sunny
    #     name: Switch to system preference
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  # icon:
  #   admonition:
  #     example: fontawesome/solid/flask

markdown_extensions:
  - admonition
  - def_list
  - attr_list
  - callouts
  - footnotes
  # - md_in_html
  - meta
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - markdown.extensions.toc:
        slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
        permalink: ""

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


plugins:
  # - markdown-exec
  - search:
      lang: en
  - mkdocs-video:
      is_video: True
      video_muted: False
      video_controls: True
      css_style:
        width: "50%"

extra:
  analytics:
    provider: google
    property: G-VHR0GFBR7Q
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yappstore
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yappstore_ai
    - icon: fontawesome/brands/discord
      link: https://discord.gg/9vdvUDz22V

copyright: Copyright © 2024 yappstore.ai | The Yapp Store
